class Quote {
  final String text;
  final String author;

  Quote(this.text, this.author);
}

class QuotesData {
  static List<Quote> goodDopamineQuotes = [
    Quote("Believe you can and you're halfway there.", "Theodore Roosevelt"),
    Quote("Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau"),
    Quote("What you do today can improve all your tomorrows.", "Ralph Marston"),
    Quote("Keep your eyes on the stars, and your feet on the ground.", "Theodore Roosevelt"),
    Quote("You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"),
    Quote("The best way to predict your future is to create it.", "Peter Drucker"),
    Quote("Act as if what you do makes a difference. It does.", "William James"),
    Quote("Success is not in what you have, but who you are.", "Bo Bennett"),
    Quote("Life is either a daring adventure or nothing at all.", "Helen Keller"),
    Quote("Success is how high you bounce when you hit bottom.", "General George Patton"),
    Quote("Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.", "Kerry Washington"),
    Quote("Don’t watch the clock; do what it does. Keep going.", "Sam Levenson"),
    Quote("Everything you’ve ever wanted is on the other side of fear.", "George Addair"),
    Quote("Success is not final; failure is not fatal: It is the courage to continue that counts.", "Winston Churchill"),
    Quote("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"),
    Quote("You can’t change the direction of the wind, but you can adjust your sails to always reach your destination.", "Jimmy Dean"),
    Quote("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    Quote("Your time is limited, so don’t waste it living someone else’s life.", "Steve Jobs"),
    Quote("You are braver than you believe, stronger than you seem, and smarter than you think.", "A.A. Milne"),
    Quote("Keep your eyes on the stars, and your feet on the ground.", "Theodore Roosevelt"),
    Quote("You can’t use up creativity. The more you use, the more you have.", "Maya Angelou"),
    Quote("The only way to do great work is to love what you do.", "Steve Jobs"),
    Quote("Life is 10% what happens to you and 90% how you react to it.", "Charles R. Swindoll"),
    Quote("What you think, you become.", "Buddha"),
    Quote("Success is walking from failure to failure with no loss of enthusiasm.", "Winston Churchill"),
    Quote("The journey of a thousand miles begins with a single step.", "Lao Tzu"),
    Quote("Keep your face always toward the sunshine—and shadows will fall behind you.", "Walt Whitman"),
    Quote("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    Quote("Opportunities don't happen, you create them.", "Chris Grosser"),
    Quote("The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
    Quote("Success is not just about what you accomplish in your life; it's about what you inspire others to do.", "Unknown"),
    Quote("Don't wait for opportunity. Create it.", "George Bernard Shaw"),
    Quote("With the new day comes new strength and new thoughts.", "Eleanor Roosevelt"),
    Quote("Dream big and dare to fail.", "Norman Vaughan"),
    Quote("The best way to find yourself is to lose yourself in the service of others.", "Mahatma Gandhi"),
    Quote("You must be the change you wish to see in the world.", "Mahatma Gandhi"),
    Quote("To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "Ralph Waldo Emerson"),
    Quote("You are enough just as you are.", "Oprah Winfrey"),
    Quote("Success is how high you bounce when you hit bottom.", "General George Patton"),
    Quote("In the middle of every difficulty lies opportunity.", "Albert Einstein"),
    Quote("The way to get started is to quit talking and begin doing.", "Walt Disney"),
    Quote("Challenges are what make life interesting; overcoming them is what makes life meaningful.", "Joshua J. Marine"),
    Quote("Hardships often prepare ordinary people for an extraordinary destiny.", "C.S. Lewis"),
    Quote("Success is not measured by what you accomplish, but the opposition you have encountered.", "Orison Swett Marden"),
    Quote("Everything you can imagine is real.", "Pablo Picasso"),
    Quote("Your only limit is you.", "Unknown"),
    Quote("Don't limit your challenges, challenge your limits.", "Unknown"),
    Quote("The harder you work for something, the greater you'll feel when you achieve it.", "Unknown"),
    Quote("Dream it. Wish it. Do it.", "Unknown"),
    Quote("Sometimes we're tested not to show our weaknesses, but to discover our strengths.", "Unknown"),
    Quote("The secret of getting ahead is getting started.", "Mark Twain"),
    Quote("Great things are done by a series of small things brought together.", "Vincent Van Gogh"),
    Quote("Success is not how high you have climbed, but how you make a positive difference to the world.", "Roy T. Bennett"),
    Quote("Stay positive, work hard, make it happen.", "Unknown"),
    Quote("Believe you can and you’re halfway there.", "Theodore Roosevelt"),
    Quote("Dream big. Work hard. Stay focused.", "Unknown"),
    Quote("Positive anything is better than negative nothing.", "Elbert Hubbard"),
    Quote("Success is not in what you have, but who you are.", "Bo Bennett"),
  ];

  static List<Quote> badDopamineQuotes = [
    Quote("Fear is a choice.", "Anonymous"),
    Quote("Let go of what weighs you down.", "Buddha"),
    Quote("Your past does not define you.", "Tony Robbins"),
    Quote("What you allow is what continues.", "Anonymous"),
    Quote("Mistakes are lessons learned.", "Anonymous"),
    Quote("Change your mindset, change your life.", "Anonymous"),
    Quote("Every setback is a setup for a comeback.", "T.D. Jakes"),
    Quote("Your life is your message.", "Mahatma Gandhi"),
    Quote("Learn from yesterday, live for today.", "Anonymous"),
    Quote("Take a deep breath and let it go.", "Anonymous"),
    Quote("The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"),
    Quote("In the middle of every difficulty lies opportunity.", "Albert Einstein"),
    Quote("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    Quote("The best way out is always through.", "Robert Frost"),
    Quote("Don't let yesterday take up too much of today.", "Will Rogers"),
    Quote("If you want to live a happy life, tie it to a goal, not to people or things.", "Albert Einstein"),
    Quote("You miss 100% of the shots you don’t take.", "Wayne Gretzky"),
    Quote("Sometimes you win, sometimes you learn.", "John Maxwell"),
    Quote("Our greatest glory is not in never falling, but in rising every time we fall.", "Confucius"),
    Quote("The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"),
    Quote("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"),
    Quote("You can't use up creativity. The more you use, the more you have.", "Maya Angelou"),
    Quote("You cannot escape the responsibility of tomorrow by evading it today.", "Abraham Lincoln"),
    Quote("Don't count the days, make the days count.", "Muhammad Ali"),
    Quote("It's not whether you get knocked down, it's whether you get up.", "Vince Lombardi"),
    Quote("You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"),
    Quote("The only limit to our realization of tomorrow is our doubts of today.", "Franklin D. Roosevelt"),
    Quote("What we fear doing most is usually what we most need to do.", "Tim Ferriss"),
    Quote("When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.", "Helen Keller"),
    Quote("We may encounter many defeats but we must not be defeated.", "Maya Angelou"),
    Quote("If you want to succeed, you have to be willing to be uncomfortable.", "T. Harv Eker"),
    Quote("It's not about how hard you hit; it's about how hard you can get hit and keep moving forward.", "Rocky Balboa"),
    Quote("Fall seven times and stand up eight.", "Japanese Proverb"),
    Quote("You may have to fight a battle more than once to win it.", "Margaret Thatcher"),
    Quote("Life is 10% what happens to you and 90% how you react to it.", "Charles R. Swindoll"),
    Quote("Doubt kills more dreams than failure ever will.", "Suzy Kassem"),
    Quote("Failure is not the opposite of success; it's part of success.", "Arianna Huffington"),
    Quote("Success is not how high you have climbed, but how you make a positive difference to the world.", "Roy T. Bennett"),
    Quote("What we think, we become.", "Buddha"),
    Quote("You don't have to be great to start, but you have to start to be great.", "Zig Ziglar"),
    Quote("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    Quote("Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", "Unknown"),
    Quote("Your time is limited, so don’t waste it living someone else’s life.", "Steve Jobs"),
    Quote("You have power over your mind—not outside events. Realize this, and you will find strength.", "Marcus Aurelius"),
    Quote("You are enough just as you are.", "Oprah Winfrey"),
    Quote("Every day may not be good, but there's something good in every day.", "Alice Morse Earle"),
    Quote("The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"),
    Quote("Life isn't about finding yourself. Life is about creating yourself.", "George Bernard Shaw"),
    Quote("Happiness is not something ready-made. It comes from your own actions.", "Dalai Lama"),
    Quote("Success is not in what you have, but who you are.", "Bo Bennett"),
    Quote("The way to get started is to quit talking and begin doing.", "Walt Disney"),
    Quote("Do not wait to strike till the iron is hot, but make it hot by striking.", "William Butler Yeats"),
    Quote("You will never win if you never begin.", "Helen Rowland"),
    Quote("Life is either a daring adventure or nothing at all.", "Helen Keller"),
    Quote("The most common way people give up their power is by thinking they don’t have any.", "Alice Walker"),
  ];
}
